### ISSUE TITLE
Unit tests script returns an error

### ISSUE THREAD

**Issue by Moshe-Kessler** [duckbeartrap/zooz#4]
When running `npm run test-unit` I get the following error:
zooz@0.0.0 test-unit /Users/moshe/projects/zooz
> jest --config jest-unit.config.js

● Validation Error:

  Preset jest-preset-angular is invalid:

  The "id" argument must be of type string. Received null
  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received null
    at validateString (internal/validators.js:121:11)
    at Module.require (internal/modules/cjs/loader.js:1083:3)
    at require (internal/modules/cjs/helpers.js:75:18)
    at setupPreset (/usr/local/lib/node_modules/jest/node_modules/jest-config/build/normalize.js:289:14)
    at normalize (/usr/local/lib/node_modules/jest/node_modules/jest-config/build/normalize.js:642:15)
    at readConfig (/usr/local/lib/node_modules/jest/node_modules/jest-config/build/index.js:224:68)
    at async readConfigs (/usr/local/lib/node_modules/jest/node_modules/jest-config/build/index.js:404:26)
    at async runCLI (/usr/local/lib/node_modules/jest/node_modules/@jest/core/build/cli/index.js:230:59)
    at async Object.run (/usr/local/lib/node_modules/jest/node_modules/jest-cli/build/cli/index.js:163:37)

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

<img width="801" alt="unit-tests-script-error" src="https://user-images.githubusercontent.com/48452403/88477287-0e6af000-cf3f-11ea-9c75-e563c952f992.png">

**Comment by duckbeartrap** [comment]
Hey, have you run npm install?

**Comment by Moshe-Kessler** [comment]
I did and it works 🤓

**Comment by duckbeartrap** [comment]
Great 😄! I might be late with my responses, but I’ll reply as soon as I
can!
